name: install-tools
description: "Install pipeline tools"

runs:
  using: composite
  steps:
    - uses: anchore/sbom-action/download-syft@ab5d7b5f48981941c4c5d6bf33aeb98fe3bae38c # v0.15.10

    - name: install grype
      env:
        # renovate: datasource=github-tags depName=anchore/grype versioning=semver
        VERSION: v0.74.6
      run: "curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin $VERSION"
      shell: bash

    - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
      with:
        go-version: 1.22.x
        cache-dependency-path: |
          **/go.sum
          **/go.mod
