name: install-tools
description: "Install pipeline tools"

runs:
  using: composite
  steps:
    - uses: anchore/sbom-action/download-syft@b6a39da80722a2cb0ef5d197531764a89b5d48c3 # v0.15.8

    - run: "curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin --tag v0.64.2"
      shell: bash

    - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
      with:
        go-version: 1.22.x
        cache-dependency-path: |
          **/go.sum
          **/go.mod

    # - name: add temp to path
    #   shell: bash
    #   run: echo "/tmp" >> $GITHUB_PATH

    #   # Once there are releases on https://github.com/defenseunicorns/maru-runner we should switch to that
    # - name: Install UDS CLI
    #   shell: bash
    #   env:
    #     VERSION: v0.9.3
    #   run: |
    #     curl --location --output /tmp/uds "https://github.com/defenseunicorns/uds-cli/releases/download/${VERSION}/uds-cli_${VERSION}_Linux_amd64"
    #     chmod +x /tmp/uds


    # - name: install revive
    #   shell: bash
    #   env:
    #     VERSION: v1.3.7
    #   run: |
    #     curl --location --output /tmp/revive.tar.gz https://github.com/mgechev/revive/releases/download/${VERSION}/revive_linux_amd64.tar.gz
    #     tar -xvf /tmp/revive.tar.gz -C /tmp/
    #     chmod +x /tmp/revive

    - name: make local bin
      shell: bash
      run: |
        mkdir -p ~/.local/bin

      # Once there are releases on https://github.com/defenseunicorns/maru-runner we should switch to that
    - name: Install UDS CLI
      shell: bash
      env:
        VERSION: v0.9.3
      run: |
        curl --location --output ~/.local/bin/uds "https://github.com/defenseunicorns/uds-cli/releases/download/${VERSION}/uds-cli_${VERSION}_Linux_amd64"
        chmod +x ~/.local/bin/uds


    - name: install revive
      shell: bash
      env:
        VERSION: v1.3.7
      run: |
        curl --location --output ~/.local/bin/revive.tar.gz https://github.com/mgechev/revive/releases/download/${VERSION}/revive_linux_amd64.tar.gz
        tar -xvf ~/.local/bin/uds/revive.tar.gz -C ~/.local/bin/
        chmod +x ~/.local/bin/revive
