name: Release Package

on:
  workflow_dispatch:
    inputs:
      packageName:
        description: "Go Sub-Package Name"
        required: true
      version:
        description: "Version"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Validate Package Name
        run: |
          PACKAGE_NAME=${{ github.event.inputs.packageName }}
          MODULES=$(find . -type f -name 'go.mod' -exec dirname {} \; | cut -c 3-)
          if ! echo "$MODULES" | grep "$PACKAGE_NAME"; then
            echo "Error: Package name '$PACKAGE_NAME' does not match any Go sub-package in the repository."
            echo "Valid packages: $MODULES"
            exit 1
          fi

      - name: Validate version
        run: |
          # https://regex101.com/r/Vu7qEb/1
          SEMVER_REGEX="^v[0-9]+\.[0-9]+\.[0-9]+$"
          if ! [[ ${{ github.event.inputs.version }} =~ $SEMVER_REGEX ]]; then
            echo "Error: Version ${{ github.event.inputs.version }} does not match the semver pattern (vMAJOR.MINOR.PATCH)."
            exit 1
          fi

      - name: install git cliffs
        env:
          # renovate: datasource=github-tags depName=orhun/git-cliff versioning=semver
          VERSION: 2.1.1
        run: |
          curl --location --output /tmp/git-cliffs.tar.gz https://github.com/orhun/git-cliff/releases/download/v${VERSION}/git-cliff-${VERSION}-x86_64-unknown-linux-gnu.tar.gz
          tar -xvzf /tmp/git-cliffs.tar.gz -C /tmp
          mv /tmp/git-cliff-${VERSION}/git-cliff /usr/local/bin/

      - name: generate release notes
        run: |
          git cliff --tag ${{ github.event.inputs.packageName }}/${{ github.event.inputs.version }} --include-path "${{ github.event.inputs.packageName }}/*" > notes.txt

      - name: Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create ${{ github.event.inputs.packageName }}/${{ github.event.inputs.version }} --notes-file notes.txt
