name: Release Helpers


on:
  push:
    branches:
      - main
    paths:
      - 'helpers/**'
  workflow_dispatch:
    inputs:
      packageName:
        description: "Go Sub-Package Name"
        required: true
      version:
        description: "Version"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Release
        uses: ./.github/actions/release
        with:
          module: "helpers"
