name: Release Package

on:
  workflow_dispatch:
    inputs:
      packageName:
        description: "Go Sub-Package Name"
        required: true
      version:
        description: "Version"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Validate Package Name
        run: |
          PACKAGE_NAME=${{ github.event.inputs.packageName }}
          MODULES=$(find . -type f -name 'go.mod' -exec dirname {} \; | cut -c 3-)
          if ! echo "$MODULES" | grep "$PACKAGE_NAME"; then
            echo "Error: Package name '$PACKAGE_NAME' does not match any Go sub-package in the repository."
            echo "Valid packages: $MODULES"
            exit 1
          fi

      - name: Validate tag
        run: |
          SEMVER_REGEX="^v[0-9]+\.[0-9]+\.[0-9]+$"
          if ! [[ ${{ github.event.inputs.version }} =~ $SEMVER_REGEX ]]; then
            echo "Error: Version ${{ github.event.inputs.version }} does not match the semver pattern (vMAJOR.MINOR.PATCH)."
            exit 1
          fi

      - name: generate release notes
        # run: git cliff --unreleased --include-path "${{ github.event.inputs.packageName }}/*" > notes.txt
        run: echo "release notes" > notes.txt

      - name: Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create ${{ github.event.inputs.packageName }}/${{ github.event.inputs.version }} --notes-file notes.txt

      # Could add a release step with git cliff
      # https://git-cliff.org/docs/integration/github
      # git cliff -u --include-path "${{ github.event.inputs.packageName }}/*"
